# train_custom.yaml
# 'mode' is required only for CLI usage
data: '/home/student/Desktop/spilkova/DP/les_1/data.yaml'
epochs: 150
imgsz: 640
batch: 8
name: 'model_A' 
pretrained: True
multi_scale: True
patience: 10
lr0: 0.01
lrf: 0.01
auto_augment: 'randaugment'